### ISSUE TITLE
Rake task 'mail:csv' fails

### ISSUE THREAD

**Issue by DavidLemayian** [documentcloud/documentcloud#141]
When I run `rake production mail:csv`, it fails with the following error:

```console
rake aborted!
ArgumentError: wrong number of arguments (0 for 1)
/home/ubuntu/documentcloud/lib/dc/statistics.rb:188:in `accounts_csv'
/home/ubuntu/documentcloud/app/mailers/lifecycle_mailer.rb:115:in `account_and_document_csvs'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/ubuntu/.gem/ruby/2.1.3/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionmailer-4.1.6/lib/action_mailer/base.rb:580:in `block in process'
/home/ubuntu/.gem/ruby/2.1.3/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/home/ubuntu/.gem/ruby/2.1.3/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/ubuntu/.gem/ruby/2.1.3/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionmailer-4.1.6/lib/action_mailer/base.rb:577:in `process'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionmailer-4.1.6/lib/action_mailer/base.rb:568:in `initialize'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionmailer-4.1.6/lib/action_mailer/base.rb:551:in `new'
/home/ubuntu/.gem/ruby/2.1.3/gems/actionmailer-4.1.6/lib/action_mailer/base.rb:551:in `method_missing'
/home/ubuntu/documentcloud/lib/tasks/mail.rake:6:in `block (2 levels) in <top (required)>'
Tasks: TOP => mail:csv
```

**Comment by nathanstitt** [comment]
Hmm.  Didn't mean to close this quite yet until we'd verified it'd fixed the issue.  I think that should work for you though, David.  Please re-open if it does not.
