### ISSUE TITLE
`DocumentsControllerTest#test_it_can_log_in_a_reviewer` failing

### ISSUE THREAD

**Issue by reefdog** [documentcloud/documentcloud#378]
Something about aab3032e508f606e2b3ffcde114c630a1709d056 is causing `DocumentsControllerTest#test_it_can_log_in_a_reviewer` to fail:

```
  1) Error:
DocumentsControllerTest#test_it_can_log_in_a_reviewer:
ActionView::Template::Error: PG::SyntaxError: ERROR:  syntax error at or near ")"
LINE 11:       and memberships.organization_id in ()
                                                   ^
:     select
      memberships.organization_id, memberships.role,
      accounts.id,                 accounts.email,
      accounts.first_name,         accounts.last_name,
      accounts.hashed_password,    accounts.identities,
      accounts.language
    from memberships
      inner join accounts on accounts.id = memberships.account_id
    where
      memberships.role in (1,2,4,0)
      and memberships.organization_id in ()
and memberships.account_id not in (323853054)
    app/models/organization.rb:75:in `populate_members_info'
    app/models/account.rb:52:in `organizations_with_accounts'
    app/views/accounts/_current_account.js.erb:2:in `_app_views_accounts__current_account_js_erb__2237533735807183194_69849718003640'
    app/views/documents/_viewer_editing_head.html.erb:10:in `_app_views_documents__viewer_editing_head_html_erb___3220778732131345346_69849761324640'
    app/views/documents/show.html.erb:27:in `_app_views_documents_show_html_erb__1281384019749071239_69849761092240'
    test/controllers/documents_controller_test.rb:27:in `test_it_can_log_in_a_reviewer'
```

**Comment by reefdog** [comment]
This no longer fails. ¯\_(ツ)_/¯
